import os
import logging
from jinja2 import Environment, FileSystemLoader
from time import perf_counter
import gradio as gr
from backend.query import query_kimi
from backend.search import retrieve
from backend.propressing import embedding

logging.basicConfig(level = logging.INFO)
logger = logging.getLogger(__name__)

env = Environment(loader = FileSystemLoader("./frontend")) # create a Jinja2 template environment
template = env.get_template("template.j2")
template_html = env.get_template("template_html.j2")

def add_text(history, text):
    if history is None:
        history = []
    history += [(text, None)]
    return history, gr.Textbox(value="", interactive = False)
# here [text, None], text means user message, None means robot message
# Textbox, value means the showing message, interactive means whether user can input text

# bot method can update the robot message
def bot(history, vs_name, api_kind, top_k: int = 3):
    query = history[-1][0]
    if not query:
        raise gr.Warning("Please submit a non-empty string as a prompt")
    logger.info("Retrieving documents...")
    doc_start = perf_counter()
    doc = retrieve(vs_name, query, k = 25, rerank = True, top_k = top_k) # search top_k relevant texts from original doc  
    doc_time = perf_counter() - doc_start
    logger.info(f"Finished Retrieving documents in {round(doc_time, 2)} seconds...")

    # render the template and the template_html
    prompt = template.render(documents = doc, query = query, history = history)
    prompt_html = template_html.render(documents = doc, query = query, history = history)

    if api_kind == "Kimi":
        query_fn = query_kimi
    else:
        raise gr.Error("API is not supported")
    
    history[-1][1] = "" # it is None before, we set is as ""

    for character in query_fn(prompt): # prompt is the text generated by template.j2; query_fn(prompt) is a generactor
        history[-1] = (history[-1][0], character)
        yield history, prompt_html
    
def var_textbox(x):
    return x

with gr.Blocks() as demo: # demo is the object of Gradio
    vs_name_state = gr.State() # vs_name_state is a variable, and it is not related to different users
    with gr.Column():
        file_input = gr.File(type = "filepath")
        upload_btn = gr.Button(value = "Upload file")
        vs_name_output = gr.Textbox(label = "Vector Store Name")

        upload_btn.click(embedding, inputs = file_input, outputs = vs_name_output).then(var_textbox, inputs = vs_name_output, outputs = vs_name_state)
        # embedding and var_textbox are methods, inputs and outputs are variables and return value
        # the second method can store the vs_name into vs_name_state variable(which is not related to different users)

        # create a chatbot part
        chatbot = gr.Chatbot(
            [],
            elem_id = "chatbot",
            avatar_images = (
                "https://aui.atlassian.com/aui/8.8/docs/images/avatar-person.svg",
                "https://huggingface.co/datasets/huggingface/brand-assets/resolve/main/hf-logo.svg",
            ),
            bubble_full_width = False,
            show_copy_button = True,
            show_share_button = True,
        )

        with gr.Row():
            txt = gr.Textbox(
                scale = 3,
                show_label = False,
                placeholder = "Enter text and press enter",
                container = False,
            )
            txt_btn = gr.Button(value = "Submit text", scale = 1)
        
        api_kind_option = gr.Radio(choices = ["Kimi"], value = "Kimi")
        api_topk_slider = gr.Slider(minimum = 1, maximum = 5, value = 3, step = 1, label = "Top-K")

        prompt_html = gr.HTML() # it will show on the page and its name is prompt_html

        txt_msg = txt_btn.click(add_text, [chatbot, txt], [chatbot, txt], queue = False).then(
            bot,
            [chatbot, vs_name_state, api_kind_option, api_topk_slider],
            [chatbot, prompt_html],
        ) # queue = False means not going into Gradio queue but running immediately

        txt_msg.then(lambda: gr.Textbox(interactive = True), None, [txt], queue = False) # txt component will be updated, lambda: gr.Textbox(interactive=True) is a funtion which returns a Textbox

        txt_msg = txt.submit(add_text, [chatbot, txt], [chatbot, txt], queue = False).then(
            bot,
            [chatbot, vs_name_state, api_kind_option, api_topk_slider],
            [chatbot, prompt_html],
        ) # this method(by entering Enter key) is same as txt_btn.click (by entering button).

        txt_msg.then(lambda: gr.Textbox(interactive = True), None, [txt], queue = False)

    demo.queue()

    demo.launch(debug = True)










    









    
